### ISSUE TITLE
testing electron with rspec

### ISSUE THREAD

**Issue by zhaque44** [ghivert/proton#1]
So I need to create a test framework to test an electron app...I was thinking of using rspec and connecting to electron with a headless driver like phantomJS or something of that nature. Do you have any advice or any github pages you can send me too?

**Comment by ghivert** [comment]
I dont get what you want to do… Maybe you need something like [Spectron](https://electron.atom.io/spectron/)?

**Comment by zhaque44** [comment]
Yes i need spectron, but written in Ruby. Is there a way to write tests for an electron client in Ruby or RSpec? Thanks a lot

**Comment by ghivert** [comment]
So if understand, you want RSpec, but on Opal to test JavaScript ? There's [Opal RSpec](https://github.com/opal/opal-rspec), but you'll have to bind Spectron with it.

**Comment by zhaque44** [comment]
Yes! I think Opal RSpec might work...I will clone this and give it a go!
