### ISSUE TITLE
Readme wrong link

### ISSUE THREAD

**Issue by shubham9411** [ghivert/proton#4]
The opalrb link in readme is not links to the original website for Opal ruby in browser.
Original link: https://opalrb.com/
Link in Readme: https://opalrb.org

**Comment by ghivert** [comment]
Hi and thanks! Could you do a PR?

**Comment by shubham9411** [comment]
Sure 👍

**Comment by shubham9411** [comment]
Please check #5

**Comment by ghivert** [comment]
Thanks for the Pull Request! Closed now.
